### ISSUE TITLE
Allow defining an Service via a YAML file

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#7]
The goal of the Service, from the [homepage's terminology](http://hackers.lookout.com/deploydb/#_terminology):

> a collection of artifacts representing a conceptual service provided to customers (e.g. "the authentication service" which might consist of the "auth.war", "puppet-mysql", "puppet-jetty" artifacts)

Current thinking around the YAML file:

```yaml
name: "Fun as a Service"
artifacts:
  - foas
  - puppet-foas
  - puppet-mysql
pipelines:
  - devtoprod
promotions:
  - manual
  - jenkins-smoke
  - status-check
```
